"""Deterministic mock provider for tests and offline development."""

from __future__ import annotations

import re

from meeting_ingest.identity import normalize_person
from meeting_ingest.provider import ProviderRequest
from meeting_ingest.schema import Attendee, ProviderResponse, ProviderSignal, SignalEvidence, Topic

_SPEAKER_LINE = re.compile(r"^(?:\*\*)?(?P<speaker>[^:*]+?)(?:\*\*)?(?:\s+\([^)]*\))?:")


class MockProvider:
    name = "mock"
    model_id = "none"

    def extract(self, request: ProviderRequest) -> ProviderResponse:
        attendees = _infer_attendees(request.transcript)
        signals = _mock_signals(request.transcript)
        return ProviderResponse(
            title=_title_from_source(request.source_name),
            tl_dr="Mock extraction generated a deterministic scaffold summary.",
            meeting_type="unknown",
            attendees=attendees,
            topics=[
                Topic(
                    id="T1",
                    topic="Transcript review",
                    summary="Mock provider identified the transcript as the primary source.",
                    evidence="Generated by mock provider for deterministic tests.",
                )
            ],
            communication_signals=signals,
        )


def _title_from_source(source_name: str) -> str:
    stem = source_name.rsplit(".", 1)[0]
    stem = re.sub(r"^20\d{2}[-_ ]?\d{2}[-_ ]?\d{2}[-_ ]*", "", stem)
    title = stem.replace("_", " ").replace("-", " ").strip()
    return " ".join(word.capitalize() for word in title.split()) or "Untitled Meeting"


def _infer_attendees(transcript: str) -> list[Attendee]:
    attendees: list[Attendee] = []
    seen: set[str] = set()
    for line in transcript.splitlines():
        speaker_match = _SPEAKER_LINE.match(line)
        if not speaker_match:
            continue
        raw_label = speaker_match.group("speaker").strip()
        if not raw_label or raw_label in seen:
            continue
        seen.add(raw_label)
        person = normalize_person(raw_label)
        attendees.append(
            Attendee(
                person_id=person.person_id,
                display_name=person.display_name,
                raw_labels=[person.raw_label],
                confidence=person.confidence,
            )
        )
    return attendees


def _mock_signals(transcript: str) -> list[ProviderSignal]:
    if "[mock-signal]" not in transcript:
        return []
    return [
        ProviderSignal(
            signal_type="explicit_ask",
            stakeholder_id="person-kushali",
            stakeholder_name="Kushali",
            summary="Asked for source clarity.",
            evidence=SignalEvidence(
                kind="paraphrase",
                text="The transcript fixture requested a mock signal.",
                speaker="Kushali",
            ),
            inference_level="explicit",
            confidence="high",
            topics=["fixture"],
            project_refs=["mock"],
        )
    ]
