"""Deterministic mock provider for tests and offline development."""

from __future__ import annotations

from meeting_ingest.identity import normalize_person
from meeting_ingest.provider import ProviderRequest
from meeting_ingest.schema import Attendee, ProviderResponse, Topic


class MockProvider:
    name = "mock"

    def extract(self, request: ProviderRequest) -> ProviderResponse:
        attendees = _infer_attendees(request.transcript)
        return ProviderResponse(
            title=_title_from_source(request.source_name),
            tl_dr="Mock extraction generated a deterministic scaffold summary.",
            meeting_type="unknown",
            attendees=attendees,
            topics=[
                Topic(
                    id="T1",
                    topic="Transcript review",
                    summary="Mock provider identified the transcript as the primary source.",
                    evidence="Generated by mock provider for deterministic tests.",
                )
            ],
        )


def _title_from_source(source_name: str) -> str:
    stem = source_name.rsplit(".", 1)[0]
    title = stem.replace("_", " ").replace("-", " ").strip()
    return " ".join(word.capitalize() for word in title.split()) or "Untitled Meeting"


def _infer_attendees(transcript: str) -> list[Attendee]:
    attendees: list[Attendee] = []
    seen: set[str] = set()
    for line in transcript.splitlines():
        if ":" not in line:
            continue
        raw_label = line.split(":", 1)[0].strip()
        if not raw_label or raw_label in seen:
            continue
        seen.add(raw_label)
        person = normalize_person(raw_label)
        attendees.append(
            Attendee(
                person_id=person.person_id,
                display_name=person.display_name,
                raw_labels=[person.raw_label],
                confidence=person.confidence,
            )
        )
    return attendees
